name: "Run commitlint"
on:
  pull_request:
    branches: [ 'master', 'main', 'develop' ]
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches: [ feature/* ]

jobs:
  run-commitlint:
    name: Run commitlint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Commitlint Dependencies
      id: dependencies
      run: npm install @commitlint/config-conventional
    - name: Lint commit messages
      id: commitlint
      uses: wagoid/commitlint-github-action@v6.0.2
      with:
        configFile: .commitlint.config.mjs
