name: "Merged PR followup"

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  cleanup:
    name: Delete Merged Branches
    runs-on: ubuntu-latest

    steps:
      - name: cleanup
        uses: jessfraz/branch-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
