name: "pre-release PR opened"
on:
  pull_request:
    branches:
      - master
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  process-pr-open:
    name: Process New Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install conventional commit dependencies
      id: install-cc-dependencies
      run: npm i conventional-changelog-conventionalcommits

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.10.0
      with:
        config-file-path: ./.changelog.config.js
        skip-version-file: true
        skip-commit: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 8
      id: setup-java
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: corretto
        java-version: 8

    - name: Set up maven
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        output_file: $HOME/.m2/settings.xml
        repositories: >
          [
            {
              "id": "github-packages",
              "url": "https://maven.pkg.github.com/aboveproperty/*"
            }
          ]
        servers: '[{
            "id": "github-packages",
            "username": "${{ secrets.GH_USERNAME }}",
            "password": "${{ secrets.GH_PASSWORD }}"
          }, {
            "id": "dev-nexus-abvprp",
            "username": "${{ secrets.NEXUS_USERNAME }}",
            "password": "${{ secrets.NEXUS_PASSWORD }}"
          }, {
            "id": "github",
            "username": "${{ github.actor }}",
            "password": "${{ secrets.GITHUB_TOKEN }}"
          }]'
        mirrors: >
          [
            {
              "id": "dev-nexus-abvprp",
              "name": "Above Property Nexus",
              "mirrorOf": "external:*,!github-packages",
              "url": "https://nexus.dev.abvprp.com/repository/Public-Repositories/"
            }
          ]

    - name: Build assets
      id: build-
      run: rm -rf package.json package-lock.json node_modules && mvn -Djgitver.config=.mvn/jgitver.config.develop.xml --no-transfer-progress -DuseGitHubPackages=true --file pom.xml -Dfmt.skip=true -B clean package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1

  notify:
      name: Notify on Slack
      runs-on: ubuntu-latest
      needs: [process-pr-open]
      steps:
        - uses: abinoda/slack-action@master
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          with:
            args: >-
              {\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[
              {\"type\":\"divider\"},
              {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Repository:* ${{ github.repository }}\"}},
              {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},
              {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},
              {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}},{\"type\":\"divider\"}]}
          if: success()
