name: "Push feature branch"
on:
  push:
    branches: [ feature/* ]

jobs:
  verify-feature-build:
    name: Build Feature Branch
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm

    - name: Set up JDK 17
      id: checkout
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: 17

    # - name: maven-settings-xml-action
    #   uses: whelk-io/maven-settings-xml-action@v20
    #   with:
    #     output_file: $HOME/.m2/settings.xml
    #     repositories: >
    #       [
    #         {
    #           "id": "github-packages",
    #           "url": "https://maven.pkg.github.com/aboveproperty/*"
    #         }
    #       ]
    #     servers: '[{
    #         "id": "github-packages",
    #         "username": "${{ secrets.GH_USERNAME }}",
    #         "password": "${{ secrets.GH_PASSWORD }}"
    #       }, {
    #         "id": "dev-nexus-abvprp",
    #         "username": "${{ secrets.NEXUS_USERNAME }}",
    #         "password": "${{ secrets.NEXUS_PASSWORD }}"
    #       }, {
    #         "id": "github",
    #         "username": "${{ github.actor }}",
    #         "password": "${{ secrets.GITHUB_TOKEN }}"
    #       }]'
    #     mirrors: >
    #       [
    #         {
    #           "id": "dev-nexus-abvprp",
    #           "name": "Above Property Nexus",
    #           "mirrorOf": "external:*,!github-packages",
    #           "url": "https://nexus.dev.abvprp.com/repository/Public-Repositories/"
    #         }
    #       ]

    - name: Cache local Maven repository
      uses: actions/cache@v3
      timeout-minutes: 5
      with:
        path: |
          ~/.m2/repository/*/*/*
        key: ${{ runner.os }}-m2-dependencies-owasp-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-dependencies-all-${{ hashFiles('**/pom.xml') }}
          ${{ runner.os }}-m2-dependencies-core-modules-${{ hashFiles('**/pom.xml') }}
          ${{ runner.os }}-m2-dependencies-core-modules-

    - name: Install Commitlint Dependencies
      id: dependencies
      run: npm install @commitlint/config-conventional

    - name: Lint commit messages
      id: commitlint
      uses: wagoid/commitlint-github-action@v6.0.2
      with:
        configFile: .commitlint.config.mjs
        failOnErrors: false

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v29.0.4

    #- name: Check for copyright
    #  id: check_boilerplate
    #  env:
    #    FILES: ${{ steps.changed-files.outputs.all_changed_files }}
    #  run: .github/check_boilerplate/verify-boilerplate.sh

    - name: maven package
      id: package
      run: mvn --no-transfer-progress clean package -DskipTests=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
