name: OWASP Dependency Check

on: [workflow_dispatch]

jobs:
  build:
    name: Using Java ${{ matrix.java }}
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        java: [ 11 ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        lfs: false
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-owasp-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-owasp-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: OWASP Dependency Check
      run: mvn clean package org.owasp:dependency-check-maven:aggregate --file pom.xml -Dfmt.skip=true -DskipTests=true -fae -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -DfailBuildOnCVSS=7 -Dformats=ALL
    - name: Upload scan results to GitHub Code Scanning
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: target/dependency-check-report.sarif
    - name: Remove SNAPSHOT jars from repository
      run: |
        find .m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
