name: Update copyright year(s) in source code

on:
  schedule:
    - cron: '0 3 1 1 *' # 03:00 AM on January 1

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update copyright year(s)
        run: find . \( -name '.git*' -type d -prune -o -name '.mvn*' -type d -prune -o -name target -type d -prune -o -name node_modules -type d -prune \) -o -type f -print | xargs -L1 .github/copyright-year-updater/copyright-year-updater.sh
      - name: Create a PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(yearly): update copyright'
          title: 'chore(yearly): update copyright'
          branch: feature/update_copyright
